/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hq3i80ACKAA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-background">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <div className="size-6 text-primary" />
          <span className="text-2xl font-bold text-primary">One Piece Pokedex</span>
        </Link>
        <nav className="ml-auto text-black flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Characters
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 " prefetch={false}>
            Devil Fruits
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Locations
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 " prefetch={false}>
            Login
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Socials
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Admin
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 bg-primary">
          <div className="container space-y-10 xl:space-y-16 px-4 md:px-6">
            <div className="grid gap-4 px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] text-primary-foreground">
                  Explore the World of One Piece
                </h1>
                <p className="mx-auto max-w-[700px] text-primary-foreground md:text-xl">
                  Dive into the rich and captivating world of One Piece, where legendary pirates, powerful Devil Fruits,
                  and epic adventures await.
                </p>
                <div className="mt-6">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary-foreground px-4 py-2 text-sm font-medium text-primary shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Explore Characters
                  </Link>
                </div>
              </div>
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={400}
                  alt="One Piece"
                  className="w-full max-w-[400px] rounded-xl object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-foreground">Key Features</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore the detailed information on characters, weapons, crew, special attacks, devil fruits, haki,
                  and more.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Character Info"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Character Info</h3>
                  <p className="text-muted-foreground">
                    Detailed information on the Straw Hat Pirates and other characters, including their weapons, special
                    attacks, and more.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Devil Fruits"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Devil Fruits</h3>
                  <p className="text-muted-foreground">
                    Explore the diverse and powerful Devil Fruits that grant users extraordinary abilities.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img src="/placeholder.svg" width={200} height={200} alt="Haki" className="w-full h-48 object-cover" />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Haki</h3>
                  <p className="text-muted-foreground">
                    Discover the mysterious and powerful Haki abilities that some characters possess.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Marines"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Marines</h3>
                  <p className="text-muted-foreground">
                    Learn about the powerful Marines and their role in the world of One Piece (under development).
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="grid gap-4">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary p-3 text-primary-foreground">
                    <div className="h-6 w-6" />
                  </div>
                  <h3 className="text-2xl font-bold">Character Search</h3>
                </div>
                <p className="text-muted-foreground">
                  Find any character from the One Piece universe with our powerful search tool.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Search Characters
                </Link>
              </div>
              <div className="grid gap-4">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary p-3 text-primary-foreground">
                    <div className="h-6 w-6" />
                  </div>
                  <h3 className="text-2xl font-bold">Pirate Crews</h3>
                </div>
                <p className="text-muted-foreground">
                  Explore the different pirate crews and their members in the One Piece world.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  View Pirate Crews
                </Link>
              </div>
              <div className="grid gap-4">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary p-3 text-primary-foreground">
                    <div className="h-6 w-6" />
                  </div>
                  <h3 className="text-2xl font-bold">About Marines</h3>
                </div>
                <p className="text-muted-foreground">
                  Learn more about the Marines, the law enforcement organization in the One Piece world.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Explore Marines
                </Link>
                <div className="text-sm text-muted-foreground">(Under Development)</div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-foreground">
                  Meet the Straw Hat Crew
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore the diverse and captivating characters that make up the legendary Straw Hat Pirates.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Monkey D. Luffy"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Monkey D. Luffy</h3>
                  <p className="text-muted-foreground">
                    The captain of the Straw Hat Pirates, known for his boundless energy and dream of becoming the King
                    of the Pirates.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Roronoa Zoro"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Roronoa Zoro</h3>
                  <p className="text-muted-foreground">
                    The first mate of the Straw Hat Pirates, a skilled swordsman with an unwavering determination.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img src="/placeholder.svg" width={200} height={200} alt="Nami" className="w-full h-48 object-cover" />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Nami</h3>
                  <p className="text-muted-foreground">
                    The navigator of the Straw Hat Pirates, known for her exceptional navigational skills and cunning
                    tactics.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img src="/placeholder.svg" width={200} height={200} alt="Usopp" className="w-full h-48 object-cover" />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Usopp</h3>
                  <p className="text-muted-foreground">
                    The sniper of the Straw Hat Pirates, a skilled marksman and storyteller with a knack for invention.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img src="/placeholder.svg" width={200} height={200} alt="Sanji" className="w-full h-48 object-cover" />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Sanji</h3>
                  <p className="text-muted-foreground">
                    The cook of the Straw Hat Pirates, known for his culinary expertise, chivalry, and fierce fighting
                    abilities.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Tony Tony Chopper"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Tony Tony Chopper</h3>
                  <p className="text-muted-foreground">
                    The doctor of the Straw Hat Pirates, a reindeer-human hybrid with the ability to transform and use
                    various medicinal techniques.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Nico Robin"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Nico Robin</h3>
                  <p className="text-muted-foreground">
                    The archaeologist of the Straw Hat Pirates, a former member of the Baroque Works organization with
                    the ability to sprout multiple body parts.
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-background rounded-lg overflow-hidden shadow-md">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Franky"
                  className="w-full h-48 object-cover"
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-foreground">Franky</h3>
                  <p className="text-muted-foreground">
                    The shipwright of the Straw Hat Pirates, a cyborg with impressive mechanical and engineering skills.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold text-foreground">One Piece</h3>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Characters
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Devil Fruits
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Locations
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold text-foreground">Resources</h3>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Wiki
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Forums
            </Link>
            <Link href="#"  prefetch={false} />
          </div>
        </div>
      </footer>
    </div>
  )
}
